### ISSUE TITLE
5.x not working

### ISSUE THREAD

**Issue by whotopia** [gtt-project/redmine_custom_fields_groups#21]
In the plugin Gemfile I had to update gem deface to
gem 'deface', '= 1.9.0'
(but this probably has to do with other plugin dependencies I have.  

However, then  I get 

```
Zeitwerk::NameError: expected file /home/rm-base/redmine-5.0.5/plugins/redmine_customize_core_fields/app/overrides/issues/new.rb to define constant Issues::New, but didn't

      raise Zeitwerk::NameError.new(msg, cref.last)
      ^^^^^
<internal:dir>:220:in `glob'
/home/rm-base/redmine-5.0.5/config/environment.rb:16:in `<top (required)>'
/home/rm-base/.rbenv/versions/3.1.2/bin/bundle:25:in `load'
/home/rm-base/.rbenv/versions/3.1.2/bin/bundle:25:in `<main>'
Tasks: TOP => db:migrate => db:load_config => environment
(See full trace by running task with --trace)
```

help?

**Comment by sanak** [comment]
@whotopia The above error tells that `redmine_customize_core_fields` plugin raises error.
I am not sure whether the error only happens with combination of [this plugin](https://github.com/gtt-project/redmine_custom_fields_groups) and [that plugin](https://github.com/nanego/redmine_customize_core_fields), but asking the error in that side may be also better.
https://github.com/nanego/redmine_customize_core_fields/issues

From the following issue's history, updating `redmine_customize_core_fields` plugin may solve the issue.
https://github.com/nanego/redmine_customize_core_fields/issues/16

**Comment by sanak** [comment]
@whotopia
[redmine_customize_core_fields](https://github.com/nanego/redmine_customize_core_fields) plugin seems to support Redmine 5.x.
Could you try to check this on your environment again ?

**Comment by sanak** [comment]
Well, I close this issue.
