### ISSUE TITLE
Typo "expended"

### ISSUE THREAD

**Issue by dkastl** [gtt-project/redmine_custom_fields_groups#29]
Typo "expended" should be "expanded"

**Comment by sanak** [comment]
@dkastl Oh, this issue already exists in #27.

About CSS `expended`, it is correct until Redmine < 5.0.0.
Please check PR:#26.
>  - Fix CSS class typo `expended` in Redmine >= 5.0.0
>  - [Defect #36149: Typo in CSS class for lists expander icon - Redmine](https://www.redmine.org/issues/36149)

**Comment by dkastl** [comment]
Ah, I see. I didn't think there is already an issue.

**Comment by dkastl** [comment]
closing as duplicate.
